// SPDX-FileCopyrightText: 2025-2026 Trinadh Thatakula <github.com/trinadhthatakula/Thor>
// SPDX-License-Identifier: GPL-3.0-or-later

package com.valhalla.thor.data.backup

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyPermanentlyInvalidatedException
import android.security.keystore.KeyProperties
import androidx.datastore.core.handlers.ReplaceFileCorruptionHandler
import androidx.datastore.preferences.core.edit
import androidx.datastore.preferences.core.emptyPreferences
import androidx.datastore.preferences.core.stringPreferencesKey
import androidx.datastore.preferences.preferencesDataStore
import com.valhalla.thor.util.Logger
import java.io.IOException
import java.nio.ByteBuffer
import java.nio.CharBuffer
import java.security.KeyStore
import java.util.Base64
import javax.crypto.AEADBadTagException
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.catch
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.map
import org.koin.core.annotation.Single

/**
 * The shortest passphrase Thor accepts **where one is chosen** — the backup sheet (Task 16) and the
 * Settings screen (Task 18).
 *
 * Deliberately *not* applied where a passphrase is typed to **unlock** an archive. An archive written
 * before this rule existed may have a four-character passphrase, and a minimum on the unlock field
 * would lock it out permanently. Public and top-level so the two places that choose a passphrase
 * cannot drift to different numbers.
 */
const val MIN_PASSPHRASE_LENGTH = 8

/**
 * Wraps and unwraps a few bytes under a key Thor does not hold itself.
 *
 * A seam, not indirection for its own sake: `AndroidKeyStore` cannot be exercised on the JVM, and
 * the contract worth testing is what happens when the key is **gone**.
 */
interface VaultKeyProvider {
    fun wrap(plaintext: ByteArray): ByteArray

    /** @throws java.security.GeneralSecurityException when the key is gone or invalidated. */
    fun unwrap(blob: ByteArray): ByteArray
}

/** Where the wrapped passphrase lives. Separated so the vault's logic is JVM-testable. */
interface PassphraseVaultStore {
    /** Whether a blob is stored. Not whether it can still be unwrapped — see [PassphraseVault.recall]. */
    val isSet: Flow<Boolean>
    suspend fun read(): String?
    suspend fun write(value: String?)
}

private const val KEY_ALIAS = "thor.archive.passphrase.v1"
private const val GCM_TAG_BITS = 128
private const val GCM_IV_BYTES = 12

@Single(binds = [VaultKeyProvider::class])
class AndroidKeystoreVaultKeyProvider : VaultKeyProvider {

    override fun wrap(plaintext: ByteArray): ByteArray {
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.ENCRYPT_MODE, key())
        // The IV is generated by the Keystore and must be carried with the ciphertext.
        return cipher.iv + cipher.doFinal(plaintext)
    }

    override fun unwrap(blob: ByteArray): ByteArray {
        require(blob.size > GCM_IV_BYTES) { "wrapped passphrase is too short" }
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(
            Cipher.DECRYPT_MODE,
            key(),
            GCMParameterSpec(GCM_TAG_BITS, blob, 0, GCM_IV_BYTES),
        )
        return cipher.doFinal(blob, GCM_IV_BYTES, blob.size - GCM_IV_BYTES)
    }

    private fun key(): SecretKey {
        val store = KeyStore.getInstance("AndroidKeyStore").apply { load(null) }
        (store.getEntry(KEY_ALIAS, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, "AndroidKeyStore")
        generator.init(
            KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                // API 28, which is minSdk. Backup and restore are foreground, user-initiated work,
                // so the device is unlocked by definition — see spec §9.3, where this and
                // WorkManager's deferral being off are the same decision.
                .setUnlockedDeviceRequired(true)
                .build()
        )
        return generator.generateKey()
    }
}

// Corruption-handled for the same reason as PreferenceRepositoryImpl's DataStores: an interrupted
// write or bad block can leave the file unreadable, and the default handler would rethrow forever.
// Replacing with empty preferences means recall() returns null → the user is prompted to type the
// passphrase, which is exactly the failure mode this cache is designed to degrade to.
private val Context.passphraseVault by preferencesDataStore(
    name = "thor_passphrase_vault",
    corruptionHandler = ReplaceFileCorruptionHandler {
        Logger.e("PassphraseVault", "thor_passphrase_vault was unreadable; replacing with empty", it)
        emptyPreferences()
    }
)
private val WRAPPED = stringPreferencesKey("wrapped_passphrase")

@Single(binds = [PassphraseVaultStore::class])
class DataStorePassphraseVaultStore(private val context: Context) : PassphraseVaultStore {

    private val flow: Flow<String?> = context.passphraseVault.data.map { it[WRAPPED] }

    /**
     * `catch` kept from the property this replaced: the corruption handler covers an unreadable
     * *file*, but `DataStore.data` still surfaces a plain `IOException` on a failed read, and an
     * exception escaping here would tear down whichever screen is collecting. "Not remembered" is the
     * right degradation — it prompts, and prompting is always correct.
     */
    override val isSet: Flow<Boolean> = flow.map { it != null }.catch { emit(false) }

    override suspend fun read(): String? = flow.first()

    override suspend fun write(value: String?) {
        try {
            context.passphraseVault.edit { prefs ->
                if (value == null) prefs.remove(WRAPPED) else prefs[WRAPPED] = value
            }
        } catch (e: IOException) {
            Logger.e("PassphraseVault", "thor_passphrase_vault could not be written; change not saved", e)
        }
    }
}

/**
 * The remembered passphrase — **a cache, never the source of truth.**
 *
 * If the Keystore key is gone or invalidated (app reinstall, factory reset, biometric enrolment
 * change), [recall] returns null and the blob is cleared. Thor then prompts, and the archive is
 * still perfectly readable: it was only ever protected by the passphrase itself.
 *
 * Two consequences the UI must state, not imply:
 * - Changing the passphrase does **not** re-encrypt existing archives.
 * - On restore, a stored passphrase that fails the verifier means *prompt*, not *corrupt archive*.
 */
@Single
class PassphraseVault(
    private val store: PassphraseVaultStore,
    private val keyProvider: VaultKeyProvider,
) {

    /**
     * Whether a blob is stored — **not** whether it will unwrap.
     *
     * A Keystore key invalidated by a biometric re-enrolment leaves this true and [recall] null, and
     * that pair is deliberate: the caller then prompts rather than reporting a failure.
     *
     * Straight through to the store now that [PassphraseVaultStore] answers it. The downcast this
     * replaced returned a constant `false` for every store that was not the DataStore one, which made
     * the property untestable and would have read "nothing remembered" under any other backing.
     */
    val isRemembered: Flow<Boolean>
        get() = store.isSet

    /**
     * Wrap [passphrase] and store it.
     *
     * **Reports rather than throws, exactly as [recall] does.** Two things can fail: the Keystore
     * wrap, and the store write beneath it. Neither escapes — both are caught and reported as
     * `false`, so a caller cannot be handed a failure it has nowhere to put. That symmetry is the
     * point: `PassphraseSettingsViewModel.save` maps `false` to `PassphraseError.STORE_FAILED` and
     * `AppBackupViewModel.beginBackup` treats a failure to *cache* a passphrase as survivable, which
     * is what `strings_backup.xml`'s `passphrase_error_store_failed` says in as many words. A throw
     * out of here would be a store failure reported as nothing at all — or, out of a bare
     * `viewModelScope.launch`, as a dead process.
     *
     * `CancellationException` is rethrown, not reported: it is structured concurrency's own signal
     * and swallowing it breaks cancellation rather than reporting a failure.
     *
     * @return **false means the passphrase was not stored** — the Keystore key is gone or was never
     * creatable, or the store threw — and a caller must not tell the user it was saved. Task 18's
     * settings screen is the reason this is not `Unit`: "Saved" on a screen where nothing was saved is
     * how a user stops writing their passphrase down.
     *
     * True is the weaker claim of the two: it says wrapping succeeded and [PassphraseVaultStore.write]
     * returned. **It is not a receipt from disk** — [DataStorePassphraseVaultStore.write] swallows an
     * `IOException` on purpose, because a failed write must not tear down the screen that asked for it
     * — so a full or read-only data partition still returns true here. The guard added around the
     * write does not change that: it catches what that store lets *through*, and `IOException` is
     * exactly what it does not. The consequence is bounded and is the one this cache degrades to
     * everywhere: [recall] returns null on the next launch and the user is prompted.
     *
     * [passphrase] belongs to the caller and is **not** cleared here — only the byte buffer derived
     * from it is. `AppBackupViewModel.beginBackup` and `PassphraseSettingsViewModel.save` are the two
     * callers, and both wipe it themselves.
     */
    suspend fun remember(passphrase: CharArray): Boolean {
        // Encode to bytes without creating an intermediate String — a String cannot be zeroed.
        val byteBuffer = Charsets.UTF_8.encode(CharBuffer.wrap(passphrase))
        val passphraseBytes = ByteArray(byteBuffer.limit())
        byteBuffer.get(passphraseBytes)
        // hasArray() is false for direct (off-heap) ByteBuffers; Charset.encode() always returns a
        // heap buffer on the JDK, so zeroing is effective in practice — the guard is for safety.
        if (byteBuffer.hasArray()) byteBuffer.array().fill(0)

        val wrapped = try {
            keyProvider.wrap(passphraseBytes)
        } catch (e: Exception) {
            // Nothing is written: a half-written vault would claim a passphrase is stored and then
            // fail to produce it on every use.
            Logger.e("PassphraseVault", "could not wrap the passphrase", e)
            return false
        } finally {
            passphraseBytes.fill(0)
        }
        // Encoded before the guard, and outside it: a `wrapped` that is somehow not encodable is a
        // programming error, not a store failure, and folding it in here would report it as one.
        val blob = Base64.getEncoder().encodeToString(wrapped)
        return try {
            store.write(blob)
            true
        } catch (e: CancellationException) {
            throw e
        } catch (e: Exception) {
            // The half `recall()` already had and this function did without. `write` is a suspend call
            // into DataStore; it swallows `IOException` itself, so what reaches here is everything
            // else — and it used to travel all the way out through a bare `viewModelScope.launch`,
            // where an uncaught throw is a dead process rather than a message.
            Logger.e("PassphraseVault", "the wrapped passphrase could not be stored", e)
            false
        }
    }

    suspend fun recall(): CharArray? {
        return try {
            val blob = store.read() ?: return null
            // IllegalArgumentException from decode is caught below and clears the blob — an
            // unparseable Base64 blob can never succeed on retry.
            val wrapped = Base64.getDecoder().decode(blob)
            val plainBytes = keyProvider.unwrap(wrapped)
            try {
                // Decode bytes to chars without an intermediate String — a String cannot be zeroed.
                // ByteBuffer.wrap shares the plainBytes array; plainBytes.fill(0) in the finally
                // below zeros it through the same reference.
                val charBuf = Charsets.UTF_8.newDecoder().decode(ByteBuffer.wrap(plainBytes))
                CharArray(charBuf.limit()).also { result ->
                    charBuf.get(result)
                    // Same hasArray() tradeoff as in remember(): direct CharBuffers are not zeroed.
                    if (charBuf.hasArray()) charBuf.array().fill(0.toChar())
                }
            } finally {
                plainBytes.fill(0)
            }
        } catch (e: CancellationException) {
            // Ahead of the broad catch below, and not reported as a recall failure: `store.read()` is
            // a suspend call, so a view model cleared mid-read lands here, and answering "nothing is
            // remembered" to a coroutine that is being cancelled is a lie that also breaks
            // cancellation. `store.read()` is the *only* suspending call in the block — the decode
            // below it is synchronous — so nothing has been unwrapped yet and there is no key
            // material this bypasses a wipe of.
            throw e
        } catch (e: Exception) {
            Logger.e("PassphraseVault", "vault passphrase recall failed; re-prompting", e)
            // Only clear the blob for failures that are permanently unrecoverable:
            //   AEADBadTagException             — authentication tag mismatch; the ciphertext can
            //                                     never decrypt correctly under any circumstances.
            //   KeyPermanentlyInvalidatedException — the Keystore key was wiped (biometric
            //                                     enrolment change, factory reset); unrecoverable.
            //   IllegalArgumentException        — the stored blob is not valid Base64 and can
            //                                     never be decoded.
            // Do NOT clear for UserNotAuthenticatedException or generic KeyStoreException: those
            // can be transient. setUnlockedDeviceRequired(true) means the key is unavailable while
            // the device is locked — clearing there would permanently destroy the cache for a state
            // that recovers by itself once the device is unlocked.
            if (e is AEADBadTagException ||
                e is KeyPermanentlyInvalidatedException ||
                e is IllegalArgumentException
            ) {
                // Guard the clear: a failure here must not escape recall() — the never-throw
                // contract matters more than whether the stale blob is removed on this call.
                // DataStorePassphraseVaultStore.write() already catches IOException; this outer
                // guard covers anything else (e.g. a DataStore internal error).
                try {
                    store.write(null)
                } catch (clearEx: Exception) {
                    Logger.e("PassphraseVault", "could not clear stale vault blob; next launch will retry", clearEx)
                }
            }
            null
        }
    }

    suspend fun forget() = store.write(null)
}
