// SPDX-FileCopyrightText: 2025-2026 Trinadh Thatakula <github.com/trinadhthatakula/Thor>
// SPDX-License-Identifier: GPL-3.0-or-later

package com.valhalla.thor.data.backup

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import androidx.datastore.preferences.core.edit
import androidx.datastore.preferences.core.stringPreferencesKey
import androidx.datastore.preferences.preferencesDataStore
import com.valhalla.thor.util.Logger
import java.security.KeyStore
import java.util.Base64
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.map
import org.koin.core.annotation.Single

/**
 * The shortest passphrase Thor accepts **where one is chosen** — the backup sheet (Task 16) and the
 * Settings screen (Task 18).
 *
 * Deliberately *not* applied where a passphrase is typed to **unlock** an archive. An archive written
 * before this rule existed may have a four-character passphrase, and a minimum on the unlock field
 * would lock it out permanently. Public and top-level so the two places that choose a passphrase
 * cannot drift to different numbers.
 */
const val MIN_PASSPHRASE_LENGTH = 8

/**
 * Wraps and unwraps a few bytes under a key Thor does not hold itself.
 *
 * A seam, not indirection for its own sake: `AndroidKeyStore` cannot be exercised on the JVM, and
 * the contract worth testing is what happens when the key is **gone**.
 */
interface VaultKeyProvider {
    fun wrap(plaintext: ByteArray): ByteArray

    /** @throws java.security.GeneralSecurityException when the key is gone or invalidated. */
    fun unwrap(blob: ByteArray): ByteArray
}

/** Where the wrapped passphrase lives. Separated so the vault's logic is JVM-testable. */
interface PassphraseVaultStore {
    suspend fun read(): String?
    suspend fun write(value: String?)
}

private const val KEY_ALIAS = "thor.archive.passphrase.v1"
private const val GCM_TAG_BITS = 128
private const val GCM_IV_BYTES = 12

@Single(binds = [VaultKeyProvider::class])
class AndroidKeystoreVaultKeyProvider : VaultKeyProvider {

    override fun wrap(plaintext: ByteArray): ByteArray {
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.ENCRYPT_MODE, key())
        // The IV is generated by the Keystore and must be carried with the ciphertext.
        return cipher.iv + cipher.doFinal(plaintext)
    }

    override fun unwrap(blob: ByteArray): ByteArray {
        require(blob.size > GCM_IV_BYTES) { "wrapped passphrase is too short" }
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(
            Cipher.DECRYPT_MODE,
            key(),
            GCMParameterSpec(GCM_TAG_BITS, blob, 0, GCM_IV_BYTES),
        )
        return cipher.doFinal(blob, GCM_IV_BYTES, blob.size - GCM_IV_BYTES)
    }

    private fun key(): SecretKey {
        val store = KeyStore.getInstance("AndroidKeyStore").apply { load(null) }
        (store.getEntry(KEY_ALIAS, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, "AndroidKeyStore")
        generator.init(
            KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                // API 28, which is minSdk. Backup and restore are foreground, user-initiated work,
                // so the device is unlocked by definition — see spec §9.3, where this and
                // WorkManager's deferral being off are the same decision.
                .setUnlockedDeviceRequired(true)
                .build()
        )
        return generator.generateKey()
    }
}

private val Context.passphraseVault by preferencesDataStore(name = "thor_passphrase_vault")
private val WRAPPED = stringPreferencesKey("wrapped_passphrase")

@Single(binds = [PassphraseVaultStore::class])
class DataStorePassphraseVaultStore(private val context: Context) : PassphraseVaultStore {

    val flow: Flow<String?> = context.passphraseVault.data.map { it[WRAPPED] }

    override suspend fun read(): String? = flow.first()

    override suspend fun write(value: String?) {
        context.passphraseVault.edit { prefs ->
            if (value == null) prefs.remove(WRAPPED) else prefs[WRAPPED] = value
        }
    }
}

/**
 * The remembered passphrase — **a cache, never the source of truth.**
 *
 * If the Keystore key is gone or invalidated (app reinstall, factory reset, biometric enrolment
 * change), [recall] returns null and the blob is cleared. Thor then prompts, and the archive is
 * still perfectly readable: it was only ever protected by the passphrase itself.
 *
 * Two consequences the UI must state, not imply:
 * - Changing the passphrase does **not** re-encrypt existing archives.
 * - On restore, a stored passphrase that fails the verifier means *prompt*, not *corrupt archive*.
 */
@Single
class PassphraseVault(
    private val store: PassphraseVaultStore,
    private val keyProvider: VaultKeyProvider,
) {

    val isRemembered: Flow<Boolean>
        get() = (store as? DataStorePassphraseVaultStore)?.flow?.map { it != null }
            ?: kotlinx.coroutines.flow.flowOf(false)

    suspend fun remember(passphrase: CharArray) {
        val wrapped = try {
            keyProvider.wrap(passphrase.concatToString().toByteArray(Charsets.UTF_8))
        } catch (e: Exception) {
            // Nothing is written: a half-written vault would claim a passphrase is stored and then
            // fail to produce it on every use.
            Logger.e("PassphraseVault", "could not wrap the passphrase", e)
            return
        }
        store.write(Base64.getEncoder().encodeToString(wrapped))
    }

    suspend fun recall(): CharArray? {
        val blob = store.read() ?: return null
        return try {
            Base64.getDecoder().decode(blob)
                .let { keyProvider.unwrap(it) }
                .toString(Charsets.UTF_8)
                .toCharArray()
        } catch (e: Exception) {
            // The convenience layer failed, so the user types it again. Clearing it here is what
            // stops every later launch re-deriving the same failure while the UI keeps claiming a
            // passphrase is stored.
            Logger.e("PassphraseVault", "the vault key is gone; re-prompting", e)
            store.write(null)
            null
        }
    }

    suspend fun forget() = store.write(null)
}
