// SPDX-FileCopyrightText: 2025-2026 Trinadh Thatakula <github.com/trinadhthatakula/Thor>
// SPDX-License-Identifier: GPL-3.0-or-later

package com.valhalla.thor.data.backup

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyPermanentlyInvalidatedException
import android.security.keystore.KeyProperties
import androidx.datastore.core.handlers.ReplaceFileCorruptionHandler
import androidx.datastore.preferences.core.edit
import androidx.datastore.preferences.core.emptyPreferences
import androidx.datastore.preferences.core.stringPreferencesKey
import androidx.datastore.preferences.preferencesDataStore
import com.valhalla.thor.util.Logger
import java.io.IOException
import java.nio.ByteBuffer
import java.nio.CharBuffer
import java.security.KeyStore
import java.util.Base64
import javax.crypto.AEADBadTagException
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.catch
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.map
import org.koin.core.annotation.Single

/**
 * The shortest passphrase Thor accepts **where one is chosen** — the backup sheet (Task 16) and the
 * Settings screen (Task 18).
 *
 * Deliberately *not* applied where a passphrase is typed to **unlock** an archive. An archive written
 * before this rule existed may have a four-character passphrase, and a minimum on the unlock field
 * would lock it out permanently. Public and top-level so the two places that choose a passphrase
 * cannot drift to different numbers.
 */
const val MIN_PASSPHRASE_LENGTH = 8

/**
 * Wraps and unwraps a few bytes under a key Thor does not hold itself.
 *
 * A seam, not indirection for its own sake: `AndroidKeyStore` cannot be exercised on the JVM, and
 * the contract worth testing is what happens when the key is **gone**.
 */
interface VaultKeyProvider {
    fun wrap(plaintext: ByteArray): ByteArray

    /** @throws java.security.GeneralSecurityException when the key is gone or invalidated. */
    fun unwrap(blob: ByteArray): ByteArray
}

/** Where the wrapped passphrase lives. Separated so the vault's logic is JVM-testable. */
interface PassphraseVaultStore {
    suspend fun read(): String?
    suspend fun write(value: String?)
}

private const val KEY_ALIAS = "thor.archive.passphrase.v1"
private const val GCM_TAG_BITS = 128
private const val GCM_IV_BYTES = 12

@Single(binds = [VaultKeyProvider::class])
class AndroidKeystoreVaultKeyProvider : VaultKeyProvider {

    override fun wrap(plaintext: ByteArray): ByteArray {
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.ENCRYPT_MODE, key())
        // The IV is generated by the Keystore and must be carried with the ciphertext.
        return cipher.iv + cipher.doFinal(plaintext)
    }

    override fun unwrap(blob: ByteArray): ByteArray {
        require(blob.size > GCM_IV_BYTES) { "wrapped passphrase is too short" }
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(
            Cipher.DECRYPT_MODE,
            key(),
            GCMParameterSpec(GCM_TAG_BITS, blob, 0, GCM_IV_BYTES),
        )
        return cipher.doFinal(blob, GCM_IV_BYTES, blob.size - GCM_IV_BYTES)
    }

    private fun key(): SecretKey {
        val store = KeyStore.getInstance("AndroidKeyStore").apply { load(null) }
        (store.getEntry(KEY_ALIAS, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, "AndroidKeyStore")
        generator.init(
            KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                // API 28, which is minSdk. Backup and restore are foreground, user-initiated work,
                // so the device is unlocked by definition — see spec §9.3, where this and
                // WorkManager's deferral being off are the same decision.
                .setUnlockedDeviceRequired(true)
                .build()
        )
        return generator.generateKey()
    }
}

// Corruption-handled for the same reason as PreferenceRepositoryImpl's DataStores: an interrupted
// write or bad block can leave the file unreadable, and the default handler would rethrow forever.
// Replacing with empty preferences means recall() returns null → the user is prompted to type the
// passphrase, which is exactly the failure mode this cache is designed to degrade to.
private val Context.passphraseVault by preferencesDataStore(
    name = "thor_passphrase_vault",
    corruptionHandler = ReplaceFileCorruptionHandler {
        Logger.e("PassphraseVault", "thor_passphrase_vault was unreadable; replacing with empty", it)
        emptyPreferences()
    }
)
private val WRAPPED = stringPreferencesKey("wrapped_passphrase")

@Single(binds = [PassphraseVaultStore::class])
class DataStorePassphraseVaultStore(private val context: Context) : PassphraseVaultStore {

    val flow: Flow<String?> = context.passphraseVault.data.map { it[WRAPPED] }

    override suspend fun read(): String? = flow.first()

    override suspend fun write(value: String?) {
        try {
            context.passphraseVault.edit { prefs ->
                if (value == null) prefs.remove(WRAPPED) else prefs[WRAPPED] = value
            }
        } catch (e: IOException) {
            Logger.e("PassphraseVault", "thor_passphrase_vault could not be written; change not saved", e)
        }
    }
}

/**
 * The remembered passphrase — **a cache, never the source of truth.**
 *
 * If the Keystore key is gone or invalidated (app reinstall, factory reset, biometric enrolment
 * change), [recall] returns null and the blob is cleared. Thor then prompts, and the archive is
 * still perfectly readable: it was only ever protected by the passphrase itself.
 *
 * Two consequences the UI must state, not imply:
 * - Changing the passphrase does **not** re-encrypt existing archives.
 * - On restore, a stored passphrase that fails the verifier means *prompt*, not *corrupt archive*.
 */
@Single
class PassphraseVault(
    private val store: PassphraseVaultStore,
    private val keyProvider: VaultKeyProvider,
) {

    val isRemembered: Flow<Boolean>
        get() = (store as? DataStorePassphraseVaultStore)?.flow?.map { it != null }
            ?.catch { emit(false) }
            ?: kotlinx.coroutines.flow.flowOf(false)

    suspend fun remember(passphrase: CharArray) {
        // Encode to bytes without creating an intermediate String — a String cannot be zeroed.
        val byteBuffer = Charsets.UTF_8.encode(CharBuffer.wrap(passphrase))
        val passphraseBytes = ByteArray(byteBuffer.limit())
        byteBuffer.get(passphraseBytes)
        if (byteBuffer.hasArray()) byteBuffer.array().fill(0)

        val wrapped = try {
            keyProvider.wrap(passphraseBytes)
        } catch (e: Exception) {
            // Nothing is written: a half-written vault would claim a passphrase is stored and then
            // fail to produce it on every use.
            Logger.e("PassphraseVault", "could not wrap the passphrase", e)
            return
        } finally {
            passphraseBytes.fill(0)
        }
        store.write(Base64.getEncoder().encodeToString(wrapped))
    }

    suspend fun recall(): CharArray? {
        return try {
            val blob = store.read() ?: return null
            // IllegalArgumentException from decode is caught below and clears the blob — an
            // unparseable Base64 blob can never succeed on retry.
            val wrapped = Base64.getDecoder().decode(blob)
            val plainBytes = keyProvider.unwrap(wrapped)
            try {
                // Decode bytes to chars without an intermediate String — a String cannot be zeroed.
                // ByteBuffer.wrap shares the plainBytes array; plainBytes.fill(0) in the finally
                // below zeros it through the same reference.
                val charBuf = Charsets.UTF_8.newDecoder().decode(ByteBuffer.wrap(plainBytes))
                CharArray(charBuf.limit()).also { result ->
                    charBuf.get(result)
                    if (charBuf.hasArray()) charBuf.array().fill(0.toChar())
                }
            } finally {
                plainBytes.fill(0)
            }
        } catch (e: Exception) {
            Logger.e("PassphraseVault", "vault passphrase recall failed; re-prompting", e)
            // Only clear the blob for failures that are permanently unrecoverable:
            //   AEADBadTagException             — authentication tag mismatch; the ciphertext can
            //                                     never decrypt correctly under any circumstances.
            //   KeyPermanentlyInvalidatedException — the Keystore key was wiped (biometric
            //                                     enrolment change, factory reset); unrecoverable.
            //   IllegalArgumentException        — the stored blob is not valid Base64 and can
            //                                     never be decoded.
            // Do NOT clear for UserNotAuthenticatedException or generic KeyStoreException: those
            // can be transient. setUnlockedDeviceRequired(true) means the key is unavailable while
            // the device is locked — clearing there would permanently destroy the cache for a state
            // that recovers by itself once the device is unlocked.
            if (e is AEADBadTagException ||
                e is KeyPermanentlyInvalidatedException ||
                e is IllegalArgumentException
            ) {
                store.write(null)
            }
            null
        }
    }

    suspend fun forget() = store.write(null)
}
