// SPDX-FileCopyrightText: 2025-2026 Trinadh Thatakula <github.com/trinadhthatakula/Thor>
// SPDX-License-Identifier: GPL-3.0-or-later

package com.valhalla.thor.data.backup.job

import android.content.Context
import androidx.work.ExistingWorkPolicy
import androidx.work.OneTimeWorkRequest
import androidx.work.Operation
import androidx.work.WorkInfo
import androidx.work.WorkManager
import com.google.common.util.concurrent.ListenableFuture
import com.valhalla.thor.ThorApplication
import com.valhalla.thor.data.source.local.room.DataTaskDao
import com.valhalla.thor.data.source.local.room.DataTaskSnapshot
import com.valhalla.thor.domain.model.ArchiveBackupRequest
import com.valhalla.thor.domain.model.ArchiveRestoreRequest
import com.valhalla.thor.domain.model.DataTaskKind
import com.valhalla.thor.domain.model.DataTaskState
import com.valhalla.thor.domain.model.JOB_ERROR_KEY
import com.valhalla.thor.domain.model.JOB_WARNINGS_KEY
import com.valhalla.thor.domain.model.THOR_JOB_CHAIN
import com.valhalla.thor.domain.model.ThorJobKind
import com.valhalla.thor.domain.model.jobTag
import com.valhalla.thor.domain.repository.ArchiveJobLauncher
import com.valhalla.thor.domain.repository.ThorJobStatus
import com.valhalla.thor.domain.repository.ThorJobWatcher
import com.valhalla.thor.util.Logger
import java.util.UUID
import java.util.concurrent.ExecutionException
import java.util.concurrent.Executor
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlinx.coroutines.withContext
import org.koin.core.annotation.Named
import org.koin.core.annotation.Single

private const val TAG = "ThorJobLauncher"

/**
 * The one place a Thor archive job is started — and the one place one is cancelled.
 *
 * **Key derivation happens here, in the foreground, not in the worker.** PBKDF2 at 210 000 iterations
 * takes a noticeable moment, and the screen that has the passphrase is the only place with something
 * to show while it runs. It is also the only way the worker never sees a passphrase: the derived key
 * goes into [ArchiveKeyHolder] under the request's id and the passphrase stays with the caller.
 */
// ThorJobWatcher is listed explicitly even though ArchiveJobLauncher extends it: Koin binds exactly
// the types named here and does not walk a supertype chain, so `ExportJobLauncherImpl`'s delegate
// parameter would be an unresolvable dependency — and with `strictSafety` on, that fails the *build*
// rather than the first injection.
@Single(binds = [ArchiveJobLauncher::class, ThorJobWatcher::class])
class ThorJobLauncher(
    private val context: Context,
    private val keys: ArchiveKeyHolder,
    private val acceptance: DataTaskAcceptance,
    private val cancellation: DataTaskCancellationCoordinator,
    dataTaskDao: DataTaskDao,
    @Named("default") private val defaultDispatcher: CoroutineDispatcher,
    @Named("io") private val ioDispatcher: CoroutineDispatcher,
) : ArchiveJobLauncher {

    private val dataTasks = DataTaskStore(dataTaskDao)

    /**
     * @param passphrase **not cleared here.** The caller owns it — the backup sheet may still need it
     *   to write the vault, and a `CharArray` zeroed under a caller that holds a reference is a bug
     *   that only shows up on the second use.
     * @return the enqueued job's id, or null if the request could not be enqueued.
     */
    override suspend fun startBackup(
        request: ArchiveBackupRequest,
        passphrase: CharArray,
    ): UUID? {
        // On `default`, not `io`: PBKDF2 is CPU-bound, and `io`'s pool exists for threads that block.
        val taskId = try {
            withContext(defaultDispatcher) { acceptance.acceptBackup(request, passphrase) }
        } catch (cancelled: CancellationException) {
            throw cancelled
        } catch (failure: Exception) {
            Logger.e(TAG, "backup acceptance failed for ${request.packageName}", failure)
            return null
        }
        return taskId
    }

    /**
     * @param salt from the archive's **own** header (`header.kdf.salt`, Base64-decoded), not from
     *   anything Thor generated for this run. A restore derives the key from that archive's salt or it
     *   derives the wrong key — which is why this is a parameter and [startBackup] instead reads
     *   `request.salt`, generated by the sheet with `cipher.newSalt()`.
     * @param iterations from that same header, and passed on for the same reason the salt is: the
     *   default on `deriveKey` is *this build's* count, and an archive written by a Thor whose count
     *   differed would then be derived wrong from a correct passphrase. [startBackup] has no such
     *   parameter because it is the side that chooses the number and stamps it.
     *
     * Untrusted, and left to `deriveKey`'s own `require(iterations > 0)` inside the `runCatching`
     * below rather than re-checked here: `OpenArchiveUseCase.unlock` has already refused anything
     * outside `0 < n <= MAX_KDF_ITERATIONS` and derived at this very number, on the screen that
     * produced this call. A second ceiling here would be a second place to keep in step.
     */
    override suspend fun startRestore(
        request: ArchiveRestoreRequest,
        passphrase: CharArray,
        salt: ByteArray,
        iterations: Int,
    ): UUID? {
        val taskId = try {
            withContext(defaultDispatcher) {
                acceptance.acceptRestore(request, passphrase, salt, iterations)
            }
        } catch (cancelled: CancellationException) {
            throw cancelled
        } catch (failure: Exception) {
            Logger.e(TAG, "restore acceptance failed for ${request.packageName}", failure)
            return null
        }
        return taskId
    }

    /**
     * One job's state, as a screen needs it.
     *
     * `getWorkInfoByIdFlow` emits null for an id WorkManager no longer has — it prunes finished work
     * — so [ThorJobStatus.Gone] is the ordinary answer for an old id, not an error.
     */
    override fun status(jobId: UUID): Flow<ThorJobStatus> = combine(
        dataTasks.observeTask(jobId),
        WorkManager.getInstance(context).getWorkInfoByIdFlow(jobId),
    ) { task, legacy -> task?.toThorJobStatus() ?: legacy.toThorJobStatus() }

    /**
     * The unfinished job for this kind and target, if there is one.
     *
     * Active Room work is selected by its durable kind and target key. The legacy side still uses
     * [jobTag] while released [THOR_JOB_CHAIN] work drains.
     */
    override fun runningJobFor(kind: ThorJobKind, target: String): Flow<UUID?> {
        val dataKind = kind.toDataTaskKind()
        val durable = if (dataKind == null) {
            flowOf(null)
        } else {
            dataTasks.observeActiveTaskId(dataKind, target)
        }
        val legacy = WorkManager.getInstance(context)
            .getWorkInfosByTagFlow(jobTag(kind, target))
            .map { infos -> infos.firstOrNull { !it.state.isFinished }?.id }
        return combine(durable, legacy) { durableId, legacyId -> durableId ?: legacyId }
    }

    /**
     * Cancels a Room task through its task-scoped coordinator, or falls back to WorkManager for a
     * persisted legacy id. The Room lookup, rather than process-local registration, keeps routing
     * correct after process recreation.
     */
    fun cancel(jobId: UUID) {
        val application = context.applicationContext as ThorApplication
        application.launchInApplicationScope(ioDispatcher) {
            if (dataTasks.loadTask(jobId) != null) {
                cancellation.cancel(jobId)
            } else {
                keys.drop(jobId.toString())
                runCatching { WorkManager.getInstance(context).cancelWorkById(jobId) }
                    .onFailure { Logger.e(TAG, "could not cancel $jobId", it) }
            }
        }
    }
}

private fun DataTaskSnapshot.toThorJobStatus(): ThorJobStatus = when (state) {
    DataTaskState.QUEUED, DataTaskState.STAGING_SOURCE -> ThorJobStatus.Pending
    DataTaskState.RUNNING, DataTaskState.CANCEL_REQUESTED -> ThorJobStatus.Running
    DataTaskState.READY, DataTaskState.SUCCEEDED -> ThorJobStatus.Succeeded(emptyList())
    DataTaskState.READY_PARTIAL, DataTaskState.PARTIAL ->
        ThorJobStatus.Succeeded(listOfNotNull(resultCode?.value))

    DataTaskState.CANCELLED -> ThorJobStatus.Cancelled
    DataTaskState.WAITING_FOR_AUTH,
    DataTaskState.WAITING_FOR_SOURCE,
    DataTaskState.INTERRUPTED_REVIEW,
    DataTaskState.START_BLOCKED,
    DataTaskState.START_BLOCKED_NOTIFICATION,
    DataTaskState.FAILED,
    DataTaskState.EXPIRED,
        -> ThorJobStatus.Failed(resultCode?.value)
}

private fun WorkInfo?.toThorJobStatus(): ThorJobStatus = when (this?.state) {
    null -> ThorJobStatus.Gone
    WorkInfo.State.ENQUEUED, WorkInfo.State.BLOCKED -> ThorJobStatus.Pending
    WorkInfo.State.RUNNING -> ThorJobStatus.Running
    WorkInfo.State.SUCCEEDED -> ThorJobStatus.Succeeded(
        outputData.getStringArray(JOB_WARNINGS_KEY)?.toList().orEmpty()
    )

    WorkInfo.State.CANCELLED -> ThorJobStatus.Cancelled
    WorkInfo.State.FAILED -> ThorJobStatus.Failed(outputData.getString(JOB_ERROR_KEY))
}

private fun ThorJobKind.toDataTaskKind(): DataTaskKind? = when (this) {
    ThorJobKind.ARCHIVE_BACKUP -> DataTaskKind.ARCHIVE_BACKUP
    ThorJobKind.ARCHIVE_RESTORE -> DataTaskKind.ARCHIVE_RESTORE
    ThorJobKind.APP_EXPORT -> DataTaskKind.APP_EXPORT
    ThorJobKind.PRIVILEGE_SWEEP -> null
}

/**
 * Enqueue one request on a unique chain, **wait for WorkManager to say it worked**, and hand back the
 * id — or run [onAbandoned] and hand back null.
 *
 * The wait is the point. `WorkContinuation.enqueue()` does its real work on WorkManager's task
 * executor and reports the result on the returned [Operation]; catching only what is thrown
 * synchronously catches argument validation and nothing else. A `WorkSpec` insert that fails, a
 * corrupt WorkManager database, an internal executor that rejects the task — all of those arrive as a
 * failed [Operation] and were once invisible here, so this returned an id for a row that does not
 * exist.
 *
 * What that cost downstream is worth naming, because no consumer can fix it: `getWorkInfoByIdFlow`
 * emits null forever for an id with no row, [ThorJobLauncher.status] maps null to
 * [ThorJobStatus.Gone], and both watchers correctly treat a first-and-only `Gone` as "not started
 * yet" rather than as terminal. The screen then sits on a progress bar for a job that will never
 * exist, with no timeout anywhere. This is the one hole underneath that rule, and it is created here.
 *
 * **Top-level and `internal` so the next launcher shares this and not a copy of it.** It was a private
 * method on [ThorJobLauncher] while archives were the only jobs; the awaited-[Operation] handling
 * above is the part a second launcher would reimplement badly, and the only thing that actually
 * differed between the two archive call sites was the chain name.
 *
 * @param chainName the unique work name — `THOR_JOB_CHAIN` for anything that moves bytes,
 *   `THOR_SWEEP_CHAIN` for a privilege sweep. See their docs for why that split exists.
 * @param onAbandoned run only when the request will never execute, and at most once. Not run *because*
 *   the wait was cancelled — the work is with WorkManager by then and is going to run, so releasing
 *   anything it depends on would fail a live job. It is still run if the enqueue then fails, which can
 *   happen after the caller has stopped waiting; see the cancellation branch.
 */
internal suspend fun enqueueUniqueJob(
    context: Context,
    chainName: String,
    work: OneTimeWorkRequest,
    onAbandoned: (UUID) -> Unit = {},
): UUID? = enqueueUniqueJob(chainName, work, onAbandoned) {
    WorkManager.getInstance(context)
        .beginUniqueWork(chainName, ExistingWorkPolicy.APPEND_OR_REPLACE, work)
        .enqueue()
}

/**
 * Testable operation-producing half of [enqueueUniqueJob]. A sweep supplies its WorkManager adapter
 * here so its Room-to-WorkManager handoff can hold the shared process gate until this exact
 * [Operation] settles.
 */
internal suspend fun enqueueUniqueJob(
    chainName: String,
    work: OneTimeWorkRequest,
    onAbandoned: (UUID) -> Unit = {},
    enqueue: () -> Operation,
): UUID? {
    val id = work.id
    fun abandon(what: String, cause: Throwable): UUID? {
        Logger.e(TAG, "$what on $chainName", cause)
        onAbandoned(id)
        return null
    }

    val operation = try {
        enqueue()
    } catch (e: Exception) {
        return abandon("enqueue was refused", e)
    }
    return try {
        operation.awaitSuccess()
        id
    } catch (e: CancellationException) {
        // Only the *wait* was cancelled; the work is already with WorkManager and the worker that will
        // take this job's key is real. Dropping it here would fail that job for the one reason it must
        // never fail for.
        //
        // But "nobody is waiting" is not "nothing can still go wrong": the enqueue resolves on
        // WorkManager's own executor, so it can fail *after* this frame is gone, and then no worker ever
        // runs and neither `catch` below is there to see it. The future outlives the coroutine, so keep
        // watching it for that one outcome. Without this the key sits in the holder until its own
        // hour-long expiry (see [ArchiveKeyHolder.KEY_LIFETIME_MS]) with nothing left that could consume
        // it — bounded and self-clearing, but an hour of held key material for a job that does not exist.
        operation.result.whenFailed { cause ->
            abandon("enqueue failed after the wait was cancelled", cause)
        }
        throw e
    } catch (e: Exception) {
        abandon("enqueue failed", e)
    }
}

/**
 * [Operation.getResult] as a suspending call.
 *
 * WorkManager ships `Operation.await()` and it would do exactly this — but it is a
 * `public suspend inline fun` whose body calls `androidx.concurrent.futures.await`, and
 * `concurrent-futures-ktx` is a **runtime**-scope dependency of `work-runtime`. The inliner needs
 * that declaration at compile time, so the shipped extension is not reachable from here without
 * adding a dependency for one call site.
 *
 * The listener runs on whichever thread completed the future — a direct [Executor] — because all it
 * does is resume a continuation. No cancellation is propagated to the future: by the time this is
 * awaited the enqueue is already in flight, and cancelling the wait must not be mistaken for
 * cancelling the work. A `resume` on a continuation that was cancelled meanwhile is a no-op.
 *
 * Top-level and `private` to this file for the same reason the class is `@Single`: it is one
 * launcher's plumbing, not a general-purpose adapter.
 */
private suspend fun Operation.awaitSuccess(): Operation.State.SUCCESS {
    val future = result
    return suspendCancellableCoroutine { continuation ->
        future.addListener(
            {
                try {
                    continuation.resume(future.get())
                } catch (e: ExecutionException) {
                    // The future wraps the real failure; the cause is what says what went wrong.
                    continuation.resumeWithException(e.cause ?: e)
                } catch (e: Exception) {
                    continuation.resumeWithException(e)
                }
            },
            Executor { it.run() },
        )
    }
}

/**
 * Run [handle] if this future has already failed or fails later — once, and never on success.
 *
 * The counterpart to [awaitSuccess] for a caller that has stopped waiting. A `ListenableFuture` runs each
 * listener at most once and runs it immediately if it is already done, so both the "failed while nobody
 * was looking" and "failed before we registered" orders are covered without a guard flag here.
 *
 * **Only a genuine failure counts.** An [ExecutionException] is WorkManager saying the enqueue did not
 * land, and its `cause` is the reason. A cancelled future or an interrupted listener says nothing about
 * whether the `WorkSpec` was written, so this stays silent for those and lets the key expire on its own
 * timer: releasing a key a live worker still needs is the worse of the two failures.
 *
 * `internal` rather than private to this file, unlike [awaitSuccess], because it is the only part of the
 * cancellation path a JVM test can reach — [enqueueUniqueJob] itself needs `WorkManager.getInstance`, and
 * there is no `work-testing` or Robolectric on this project's test classpath.
 */
internal fun ListenableFuture<*>.whenFailed(handle: (Throwable) -> Unit) {
    addListener(
        {
            // Nothing may be thrown from here: the executor below runs this on whichever thread completed
            // the future, which is WorkManager's, and it is not expecting our exceptions.
            val cause = try {
                get()
                null
            } catch (e: ExecutionException) {
                e.cause ?: e
            } catch (_: Exception) {
                null
            }
            if (cause != null) handle(cause)
        },
        Executor { it.run() },
    )
}
