// SPDX-FileCopyrightText: 2025-2026 Trinadh Thatakula <github.com/trinadhthatakula/Thor>
// SPDX-License-Identifier: GPL-3.0-or-later

package com.valhalla.thor.data.backup.job

import android.content.Context
import androidx.work.WorkInfo
import androidx.work.WorkManager
import com.valhalla.thor.data.source.local.room.DataTaskDao
import com.valhalla.thor.data.source.local.room.DataTaskSnapshot
import com.valhalla.thor.domain.model.ArchiveBackupRequest
import com.valhalla.thor.domain.model.ArchiveRestoreRequest
import com.valhalla.thor.domain.model.DataTaskKind
import com.valhalla.thor.domain.model.DataTaskState
import com.valhalla.thor.domain.model.JOB_ERROR_KEY
import com.valhalla.thor.domain.model.JOB_WARNINGS_KEY
import com.valhalla.thor.domain.model.THOR_JOB_CHAIN
import com.valhalla.thor.domain.model.ThorJobKind
import com.valhalla.thor.domain.model.jobTag
import com.valhalla.thor.domain.model.toUserFacingJobMessage
import com.valhalla.thor.domain.repository.ArchiveJobLauncher
import com.valhalla.thor.domain.repository.ThorJobStatus
import com.valhalla.thor.domain.repository.ThorJobWatcher
import com.valhalla.thor.util.Logger
import java.util.UUID
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.withContext
import org.koin.core.annotation.Named
import org.koin.core.annotation.Single

private const val TAG = "ThorJobLauncher"

/**
 * Accepts archive jobs into the Room-backed data queue and observes new and legacy jobs.
 *
 * [DataTaskAcceptance] derives the key before accepting the task. PBKDF2 at 210 000 iterations
 * runs on the default dispatcher while the confirm sheet shows progress. Only the derived key goes
 * into [ArchiveKeyHolder] under the task's id; the passphrase stays with the caller.
 */
// ThorJobWatcher is listed explicitly even though ArchiveJobLauncher extends it: Koin binds exactly
// the types named here and does not walk a supertype chain, so `ExportJobLauncherImpl`'s delegate
// parameter would be an unresolvable dependency — and with `strictSafety` on, that fails the *build*
// rather than the first injection.
@Single(binds = [ArchiveJobLauncher::class, ThorJobWatcher::class])
class ThorJobLauncher(
    private val context: Context,
    private val acceptance: DataTaskAcceptance,
    dataTaskDao: DataTaskDao,
    @Named("default") private val defaultDispatcher: CoroutineDispatcher,
) : ArchiveJobLauncher {

    private val dataTasks = DataTaskStore(dataTaskDao)

    /**
     * @param passphrase **not cleared here.** The caller owns it — the backup sheet may still need it
     *   to write the vault, and a `CharArray` zeroed under a caller that holds a reference is a bug
     *   that only shows up on the second use.
     * @return the enqueued job's id, or null if the request could not be enqueued.
     */
    override suspend fun startBackup(
        request: ArchiveBackupRequest,
        passphrase: CharArray,
    ): UUID? {
        // On `default`, not `io`: PBKDF2 is CPU-bound, and `io`'s pool exists for threads that block.
        var acceptedTaskId: UUID? = null
        val taskId = try {
            withContext(defaultDispatcher) {
                acceptance.acceptBackup(request, passphrase) { acceptedTaskId = it }
            }
        } catch (cancelled: CancellationException) {
            throw cancelled
        } catch (failure: Exception) {
            Logger.e(TAG, "backup acceptance failed for ${request.packageName}", failure)
            return acceptedTaskId
        }
        return taskId
    }

    /**
     * @param salt from the archive's **own** header (`header.kdf.salt`, Base64-decoded), not from
     *   anything Thor generated for this run. A restore derives the key from that archive's salt or it
     *   derives the wrong key — which is why this is a parameter and [startBackup] instead reads
     *   `request.salt`, generated by the sheet with `cipher.newSalt()`.
     * @param iterations from that same header, and passed on for the same reason the salt is: the
     *   default on `deriveKey` is *this build's* count, and an archive written by a Thor whose count
     *   differed would then be derived wrong from a correct passphrase. [startBackup] has no such
     *   parameter because it is the side that chooses the number and stamps it.
     *
     * Untrusted, and left to `deriveKey`'s own `require(iterations > 0)` during acceptance
     * rather than re-checked here: `OpenArchiveUseCase.unlock` has already refused anything
     * outside `0 < n <= MAX_KDF_ITERATIONS` and derived at this very number, on the screen that
     * produced this call. A second ceiling here would be a second place to keep in step.
     */
    override suspend fun startRestore(
        request: ArchiveRestoreRequest,
        passphrase: CharArray,
        salt: ByteArray,
        iterations: Int,
    ): UUID? {
        var acceptedTaskId: UUID? = null
        val taskId = try {
            withContext(defaultDispatcher) {
                acceptance.acceptRestore(request, passphrase, salt, iterations) { acceptedTaskId = it }
            }
        } catch (cancelled: CancellationException) {
            throw cancelled
        } catch (failure: Exception) {
            Logger.e(TAG, "restore acceptance failed for ${request.packageName}", failure)
            return acceptedTaskId
        }
        return taskId
    }

    /**
     * One job's state, as a screen needs it.
     *
     * `getWorkInfoByIdFlow` emits null for an id WorkManager no longer has — it prunes finished work
     * — so [ThorJobStatus.Gone] is the ordinary answer for an old id, not an error.
     */
    override fun status(jobId: UUID): Flow<ThorJobStatus> = combine(
        dataTasks.observeTask(jobId),
        WorkManager.getInstance(context).getWorkInfoByIdFlow(jobId),
    ) { task, legacy -> task?.toThorJobStatus() ?: legacy.toThorJobStatus() }

    /**
     * The unfinished job for this kind and target, if there is one.
     *
     * Active Room work is selected by its durable kind and target key. The legacy side still uses
     * [jobTag] while released [THOR_JOB_CHAIN] work drains.
     */
    override fun runningJobFor(kind: ThorJobKind, target: String): Flow<UUID?> {
        val dataKind = kind.toDataTaskKind()
        val durable = if (dataKind == null) {
            flowOf(null)
        } else {
            dataTasks.observeActiveTaskId(dataKind, target)
        }
        val legacy = WorkManager.getInstance(context)
            .getWorkInfosByTagFlow(jobTag(kind, target))
            .map { infos -> infos.firstOrNull { !it.state.isFinished }?.id }
        return combine(durable, legacy) { durableId, legacyId -> durableId ?: legacyId }
    }
}

internal fun DataTaskSnapshot.toThorJobStatus(): ThorJobStatus = when (state) {
    DataTaskState.QUEUED, DataTaskState.STAGING_SOURCE -> ThorJobStatus.Pending
    DataTaskState.RUNNING, DataTaskState.CANCEL_REQUESTED -> ThorJobStatus.Running
    DataTaskState.READY, DataTaskState.SUCCEEDED -> ThorJobStatus.Succeeded(warnings)
    DataTaskState.READY_PARTIAL, DataTaskState.PARTIAL ->
        ThorJobStatus.Succeeded(warnings)

    DataTaskState.CANCELLED -> ThorJobStatus.Cancelled
    DataTaskState.WAITING_FOR_AUTH,
    DataTaskState.WAITING_FOR_SOURCE,
    DataTaskState.INTERRUPTED_REVIEW,
    DataTaskState.START_BLOCKED,
    DataTaskState.START_BLOCKED_NOTIFICATION,
    DataTaskState.FAILED,
    DataTaskState.EXPIRED,
        -> ThorJobStatus.Failed(failureReason ?: userFacingFallback())
}

private fun DataTaskSnapshot.userFacingFallback(): String = when (state) {
    DataTaskState.WAITING_FOR_AUTH ->
        "this archive's key is no longer in memory — start it again"

    DataTaskState.WAITING_FOR_SOURCE -> "Thor could not read that backup file"
    DataTaskState.INTERRUPTED_REVIEW ->
        "this restore stopped after it began changing the app; review it before trying again"

    DataTaskState.START_BLOCKED_NOTIFICATION ->
        "allow Thor notifications, then try the operation again"

    DataTaskState.START_BLOCKED -> "Android would not allow Thor to start the operation"
    DataTaskState.EXPIRED -> "this job expired before it could be completed"
    else -> resultCode?.toUserFacingJobMessage() ?: "the archive job could not be completed"
}

internal fun WorkInfo?.toThorJobStatus(): ThorJobStatus = when (this?.state) {
    null -> ThorJobStatus.Gone
    WorkInfo.State.ENQUEUED, WorkInfo.State.BLOCKED -> ThorJobStatus.Pending
    WorkInfo.State.RUNNING -> ThorJobStatus.Running
    WorkInfo.State.SUCCEEDED -> ThorJobStatus.Succeeded(
        outputData.getNullableStringArray(JOB_WARNINGS_KEY)?.filterNotNull().orEmpty()
    )

    WorkInfo.State.CANCELLED -> ThorJobStatus.Cancelled
    WorkInfo.State.FAILED -> ThorJobStatus.Failed(outputData.getString(JOB_ERROR_KEY))
}

internal fun ThorJobKind.toDataTaskKind(): DataTaskKind? = when (this) {
    ThorJobKind.ARCHIVE_BACKUP -> DataTaskKind.ARCHIVE_BACKUP
    ThorJobKind.ARCHIVE_RESTORE -> DataTaskKind.ARCHIVE_RESTORE
    ThorJobKind.APP_EXPORT -> DataTaskKind.APP_EXPORT
    ThorJobKind.PRIVILEGE_SWEEP -> null
}
