// SPDX-FileCopyrightText: 2025-2026 Trinadh Thatakula <github.com/trinadhthatakula/Thor>
// SPDX-License-Identifier: GPL-3.0-or-later

package com.valhalla.thor.data.backup.job

import android.content.Context
import androidx.work.ExistingWorkPolicy
import androidx.work.OneTimeWorkRequestBuilder
import androidx.work.WorkInfo
import androidx.work.WorkManager
import androidx.work.workDataOf
import com.valhalla.thor.data.backup.AppArchiveCipher
import com.valhalla.thor.domain.model.ArchiveBackupRequest
import com.valhalla.thor.domain.model.ArchiveRestoreRequest
import com.valhalla.thor.domain.model.JOB_ERROR_KEY
import com.valhalla.thor.domain.model.THOR_JOB_CHAIN
import com.valhalla.thor.domain.model.ThorJobKind
import com.valhalla.thor.domain.model.jobTag
import com.valhalla.thor.domain.repository.ArchiveJobLauncher
import com.valhalla.thor.domain.repository.ThorJobStatus
import com.valhalla.thor.util.Logger
import java.util.UUID
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.withContext
import org.koin.core.annotation.Named
import org.koin.core.annotation.Single

private const val TAG = "ThorJobLauncher"

/**
 * The one place a Thor archive job is started — and the one place one is cancelled.
 *
 * **Key derivation happens here, in the foreground, not in the worker.** PBKDF2 at 210 000 iterations
 * takes a noticeable moment, and the screen that has the passphrase is the only place with something
 * to show while it runs. It is also the only way the worker never sees a passphrase: the derived key
 * goes into [ArchiveKeyHolder] under the request's id and the passphrase stays with the caller.
 */
@Single(binds = [ArchiveJobLauncher::class])
class ThorJobLauncher(
    private val context: Context,
    private val keys: ArchiveKeyHolder,
    private val cipher: AppArchiveCipher,
    @Named("default") private val defaultDispatcher: CoroutineDispatcher,
) : ArchiveJobLauncher {

    /**
     * @param passphrase **not cleared here.** The caller owns it — the backup sheet may still need it
     *   to write the vault, and a `CharArray` zeroed under a caller that holds a reference is a bug
     *   that only shows up on the second use.
     * @return the enqueued job's id, or null if the request could not be enqueued.
     */
    override suspend fun startBackup(
        request: ArchiveBackupRequest,
        passphrase: CharArray,
    ): UUID? {
        // On `default`, not `io`: PBKDF2 is CPU-bound, and `io`'s pool exists for threads that block.
        val key = withContext(defaultDispatcher) {
            runCatching { cipher.deriveKey(passphrase, request.salt) }.getOrNull()
        } ?: run {
            Logger.e(TAG, "key derivation failed for ${request.packageName}")
            return null
        }

        val work = OneTimeWorkRequestBuilder<ArchiveBackupWorker>()
            .setInputData(workDataOf(*request.toMap().toList().toTypedArray()))
            .addTag(jobTag(ThorJobKind.ARCHIVE_BACKUP, request.packageName))
            .build()

        // Before enqueue, not after: the worker can start the instant enqueue returns, and a worker
        // that starts before its key is in the holder fails for the one reason it must never fail for.
        keys.put(work.id.toString(), key)
        return enqueue(work.id) {
            WorkManager.getInstance(context).beginUniqueWork(
                THOR_JOB_CHAIN,
                ExistingWorkPolicy.APPEND_OR_REPLACE,
                work,
            ).enqueue()
        }
    }

    /**
     * @param salt from the archive's **own** header (`header.kdf.salt`, Base64-decoded), not from
     *   anything Thor generated for this run. A restore derives the key from that archive's salt or it
     *   derives the wrong key — which is why this is a parameter and [startBackup] instead reads
     *   `request.salt`, generated by the sheet with `cipher.newSalt()`.
     */
    override suspend fun startRestore(
        request: ArchiveRestoreRequest,
        passphrase: CharArray,
        salt: ByteArray,
    ): UUID? {
        val key = withContext(defaultDispatcher) {
            runCatching { cipher.deriveKey(passphrase, salt) }.getOrNull()
        } ?: run {
            Logger.e(TAG, "key derivation failed for ${request.packageName}")
            return null
        }

        val work = OneTimeWorkRequestBuilder<ArchiveRestoreWorker>()
            .setInputData(workDataOf(*request.toMap().toList().toTypedArray()))
            .addTag(jobTag(ThorJobKind.ARCHIVE_RESTORE, request.packageName))
            .build()

        keys.put(work.id.toString(), key)
        return enqueue(work.id) {
            WorkManager.getInstance(context).beginUniqueWork(
                THOR_JOB_CHAIN,
                ExistingWorkPolicy.APPEND_OR_REPLACE,
                work,
            ).enqueue()
        }
    }

    /**
     * One job's state, as a screen needs it.
     *
     * `getWorkInfoByIdFlow` emits null for an id WorkManager no longer has — it prunes finished work
     * — so [ThorJobStatus.Gone] is the ordinary answer for an old id, not an error.
     */
    override fun status(jobId: UUID): Flow<ThorJobStatus> =
        WorkManager.getInstance(context).getWorkInfoByIdFlow(jobId).map { info ->
            when (info?.state) {
                null -> ThorJobStatus.Gone
                WorkInfo.State.ENQUEUED, WorkInfo.State.BLOCKED -> ThorJobStatus.Pending
                WorkInfo.State.RUNNING -> ThorJobStatus.Running
                WorkInfo.State.SUCCEEDED -> ThorJobStatus.Succeeded
                WorkInfo.State.CANCELLED -> ThorJobStatus.Cancelled
                // `outputData` is where the worker's own sentence is; `getString` gives null when the
                // failure came from WorkManager rather than from `fail(...)`, which Failed allows.
                WorkInfo.State.FAILED -> ThorJobStatus.Failed(info.outputData.getString(JOB_ERROR_KEY))
            }
        }

    /**
     * The unfinished job for this kind and target, if there is one.
     *
     * By tag, not by chain name: every job shares [THOR_JOB_CHAIN], so the chain cannot tell one
     * package's backup from another's. [jobTag] can, which is what it exists for.
     */
    override fun runningJobFor(kind: ThorJobKind, target: String): Flow<UUID?> =
        WorkManager.getInstance(context)
            .getWorkInfosByTagFlow(jobTag(kind, target))
            .map { infos -> infos.firstOrNull { !it.state.isFinished }?.id }

    /**
     * Cancel a job this launcher started, dropping its key **first**.
     *
     * The order is the whole point. `ThorJobWorker`'s `finally` drops the key on every path its
     * `doWork` can reach, but a job cancelled between [ArchiveKeyHolder.put] and WorkManager actually
     * *starting* `doWork` never reaches it — `doWork` is never called, so no `finally` runs, and the
     * derived key would stay in the process's memory until Thor is killed. That window is exactly the
     * branch the base worker's own comment defers to this class.
     *
     * Dropping first also makes the ordering safe the other way round: if the worker is already
     * running, it has already `take`n the key and this drop is a no-op on an absent entry.
     *
     * **This covers only an explicit cancel.** A job can also be cancelled with nobody calling this:
     * `beginUniqueWork(…, APPEND_OR_REPLACE, …)` appends to a live chain as a *dependent*, and
     * WorkManager cancels the dependents of a prerequisite that returns `Result.failure()` — so a
     * failed backup cancels the restore queued behind it, `doWork` never runs, and nothing here
     * observes it. That branch is closed by [ArchiveKeyHolder]'s own expiry rather than by an observer
     * here: the policy came from the plan and is not this class's to change, and an expiry can be
     * pinned by a JVM test where a `WorkInfo` observer cannot.
     */
    fun cancel(jobId: UUID) {
        keys.drop(jobId.toString())
        runCatching { WorkManager.getInstance(context).cancelWorkById(jobId) }
            .onFailure { Logger.e(TAG, "could not cancel $jobId", it) }
    }

    /** Drops the key if the enqueue itself throws — otherwise key material sits in memory for a job that will never run. */
    private inline fun enqueue(id: UUID, block: () -> Unit): UUID? =
        runCatching { block(); id }.getOrElse {
            Logger.e(TAG, "enqueue failed", it)
            keys.drop(id.toString())
            null
        }
}
