// SPDX-FileCopyrightText: 2025-2026 Trinadh Thatakula <github.com/trinadhthatakula/Thor>
// SPDX-License-Identifier: GPL-3.0-or-later

package com.valhalla.thor.presentation.theme

import androidx.compose.ui.graphics.Color

val greenLight = Color(0xff4c662b)
val greenDark = Color(0xffb1d18a)

val OnTertiary = Color(0xff3f3386)
val OnPrimaryFixed = Color(0xff2d460f)
val TertiaryFixedDim = Color(0xffaca0fb)
val SurfaceContainerLow = Color(0xff131313)
val Secondary = Color(0xffc7c4dd)
val Background = Color(0xff0e0e0e)
val OnSecondaryFixedVariant = Color(0xff5e5d72)
val ErrorDim = Color(0xffc74c2f)
val OutlineVariant = Color(0xff484848)
val TertiaryFixed = Color(0xffbaafff)
val OnPrimaryFixedVariant = Color(0xff486329)
val Tertiary = Color(0xffc8bfff)
val OnBackground = Color(0xffe5e5e5)
val PrimaryFixed = Color(0xffcceda4)
val OnSecondary = Color(0xff3f3e52)
val InverseSurface = Color(0xfff9f9f9)
val OnPrimary = Color(0xff4c672c)
val PrimaryDim = Color(0xffcff0a6)
val OnTertiaryFixedVariant = Color(0xff3e3285)
val OnTertiaryFixed = Color(0xff1e0b66)
val OnTertiaryContainer = Color(0xff35287c)
val OnPrimaryContainer = Color(0xff445e25)
val TertiaryContainer = Color(0xffbaafff)
val SurfaceBright = Color(0xff2c2c2c)
val SurfaceTint = Color(0xfff0ffd7)
val SurfaceDim = Color(0xff0e0e0e)
val SurfaceContainerHigh = Color(0xff1f1f1f)
val SurfaceContainer = Color(0xff191919)
val Error = Color(0xfffe7453)
val SurfaceContainerLowest = Color(0xff000000)
val InverseOnSurface = Color(0xff555555)
val Outline = Color(0xff757575)
val SecondaryFixedDim = Color(0xffdad7f1)
val Primary = Color(0xfff0ffd7)
val SecondaryDim = Color(0xffb9b6ce)
val SecondaryFixed = Color(0xffe9e5ff)
val InversePrimary = Color(0xff4c672c)
val OnError = Color(0xff450900)
val Surface = Color(0xff0e0e0e)
val SecondaryContainer = Color(0xff242436)
val OnSecondaryContainer = Color(0xffa4a1b9)
val TertiaryDim = Color(0xffa195ef)
val OnSurfaceVariant = Color(0xffababab)
val OnSurface = Color(0xffe5e5e5)
val ErrorContainer = Color(0xff881f05)
val PrimaryFixedDim = Color(0xffbfdf97)
val SurfaceContainerHighest = Color(0xff262626)
val PrimaryContainer = Color(0xffd5f6ab)
val SurfaceVariant = Color(0xff262626)
val OnSecondaryFixed = Color(0xff424155)
val OnErrorContainer = Color(0xffff9b82)

// --- LIGHT THEME (Asgardian Technical Alchemist) ---
val LightSurface = Color(0xfff8faf3)
val LightSurfaceContainer = Color(0xffedefe8)
val LightSurfaceContainerHighest = Color(0xffe1e3dd)
val LightSurfaceContainerHigh = Color(0xffe7e9e2)
val LightSurfaceContainerLow = Color(0xfff2f4ed)
val LightSurfaceContainerLowest = Color(0xffffffff)
val LightPrimary = Color(0xff354e15)
val LightOnPrimary = Color(0xffffffff)
val LightPrimaryContainer = Color(0xff4c662b)
val LightOnPrimaryContainer = Color(0xfff0ffd7)
val LightSecondary = Color(0xff55624c)
val LightOnSecondary = Color(0xffffffff)
val LightSecondaryContainer = Color(0xffd9e7cb)
val LightOnSecondaryContainer = Color(0xff131f0d)
val LightTertiary = Color(0xff66355d)
val LightOnTertiary = Color(0xffffffff)
val LightTertiaryContainer = Color(0xfff8d8ee)
val LightOnTertiaryContainer = Color(0xff2d112b)
val LightOnSurface = Color(0xff191c18)
val LightOnSurfaceVariant = Color(0xff43493e)
val LightOutline = Color(0xff74796d)
val LightOutlineVariant = Color(0xffc3c8bc)
val LightError = Color(0xffba1a1a)
val LightOnError = Color(0xffffffff)
val LightErrorContainer = Color(0xffffdad6)
val LightOnErrorContainer = Color(0xff410002)
